export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const NOVO_JOGO_REQUEST = 'NOVO_JOGO_REQUEST';
export const NOVO_JOGO_SUCCESS = 'NOVO_JOGO_SUCCESS';
export const NOVO_JOGO_FAILURE = 'NOVO_JOGO_FAILURE';

export const FAZER_MOVIMENTO_REQUEST = 'FAZER_MOVIMENTO_REQUEST';
export const FAZER_MOVIMENTO_SUCCESS = 'FAZER_MOVIMENTO_SUCCESS';
export const FAZER_MOVIMENTO_FAILURE = 'FAZER_MOVIMENTO_FAILURE';

// manter o token
export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
